# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Term-TtyRec-Plus
version:      0.05
version_from: lib/Term/TtyRec/Plus.pm
installdirs:  site
requires:
    IO::Uncompress::Bunzip2:       0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
